### PR TITLE
Move data transfer to after checks

### PR DESCRIPTION
**Pull request by wbenoit26**
We were occasionally trying to do `X.to(device)` when `X` was `None`, so I moved that line to after the checks are performed.

### CODE REVIEW

**Comment by wbenoit26** [comment]
@EthanMarx do you know why it's looking for `pytest` when we don't have any tests set up for `online`?

**Comment by EthanMarx** [comment]
We need to add a dummy `tests` folder and a dummy `test.py` for now. (Should also give us sufficient motivation to fill it out with real tests)

**Comment by EthanMarx** [comment]
Can you do that here?

**Comment by wbenoit26** [comment]
@EthanMarx should be good to go now

**Review by EthanMarx — APPROVED** [review]

**Pull request merged**
