### PR TITLE
Library p_astro

### PR DESCRIPTION
**Pull request by wbenoit26**
Moves the p_astro functionality into the `ledger` library. @EthanMarx, would love some feedback on this. I doesn't really feel like these functions integrate all the neatly, so let me know if you have any thoughts/ideas.

### CODE REVIEW

**Comment by EthanMarx** [comment]
Okay yeah this doesn't seem like it should integrate directly into the `ledger`. The `EventSet` can represent 0lag data, for which we don't wan't this functionality attached. 

These honestly are probably best implemented as functions similarly to what you had before. I think what we should do is just make this a `p_astro` lib that has `ledger` as as a dep.

```python
F = TypeVar("F", np.ndarray, float)

def fit_noise_model(background: EventSet) -> callable[F, F]:

    # perform kde on bulk
    kde = gaussian_kde(background.detection_statistic)
    polynomial = polynomial_fit(background.detection_statistic)
    
    # return noise_model that is some sort of callable-like
    # object that given a det stat gives noise the rate; 
    # use np.piecewise to build model from kde and polynomial 
    model = np.piecewise()
    return model
  
def fit_signal_model(
    rejected: RejectedParameterSet,
    foreground: RecoveredInjectionSet,
    astro_event_rate: float,
    cosmology: astropy.Cosmology,
) -> callable[F, F]:

    # get injected volume from min/max redshifts
    # of the union of rejected parameter set and actual injections
    injected_volume = get_injected_volume(cosmology, zmin, zmax, dec_min, dec_max)
    
     
    # do signal model fitting
    return model
    
# some helper function for doing the whole fitting from our ledger objects
def fit_p_astro(background: EventSet, foreground: RecoveredInjectionSet, rejected: RejectedParameterSet) -> callable[F, F]:
    noise_model = fit_noise_model()
    signal_model = fit_signal_model()
        
    def p_astro(stats: np.ndarray):
        noise_rate = noise_model(stats)
        foreground_rate = signal_model(rate)
        return  foreground_rate / (foreground_rate + noise_rate)
            
    return p_astro
    
```

So then the main entrypoint will just be the `fit_p_astro` function that does the noise and signal fitting via the helper functions for you and returns a callable object that takes det stats and returns p_astros

**Comment by wbenoit26** [comment]
I think this is more or less good. One pain point that remains is the amount of time it takes to estimate where to begin use the exponential fit of the background distribution. Honestly, I think we could just use our knowledge of what the background distribution looks like to pick a point

**Comment by EthanMarx** [comment]
This looks great, a couple of things:

1. We should be consistent with notation (either foreground + background, or signal + noise, my vote for the former)
2. Do we ensure that the 2 fits are continuous at the boundary?

**Comment by EthanMarx** [comment]
Also it seems like you got this working so maybe this just isn't committed but I think the piecewise needs to be something like

```python
def noise_model(stats: F) -> F:
        return (
            np.piecewise(
                stats,
                [stats < threshold_statistic, stats >= threshold_statistic],
                [kde, lambda x: np.exp(fit(x))],
            )
            * scale_factor
        )
```

**Comment by EthanMarx** [comment]
The `p_astro` callable also breaks for single floats

**Comment by wbenoit26** [comment]
1. Agreed, and I share your preference for background/foreground.
2. There's nothing to enforce that the functions have the same value at the boundary, but in practice they're within some small delta of each other. Maybe we have a check on the relative difference that raises a warning if we exceed some tolerance. I'm not sure that we want to enforce perfect continuity: if the values a very difference, it's because the KDE has done something strange right before getting to the fit regime. 
3. I'm fine with doing things that way. The main reason for it is that evaluation of the background KDE often takes a long time, but we can just only pass statistics above some threshold in the first place.
4. Yeah, will do.
5. That sounds good to me.
6. Oops, yeah, things were working for me because all of the statistics were in the fit regime anyway.
7.  Good point, will fix

**Review by EthanMarx — APPROVED** [review]

**Pull request merged**
